<div class="m-4">
  <h1 class="default-header">OpenFPL Revenue Streams</h1>
  <p class="my-4">
    OpenFPL's revenue model is thoughtfully designed to sustain and grow the DAO
    while ensuring practical utility and value for its users.
  </p>

  <h2 class="default-header">Diversified Revenue Model</h2>
  <p class="my-2">
    To avoid creating a supply shock by pegging services to a fixed token
    amount, OpenFPL's revenue streams are diversified. This approach mitigates
    the risk of reduced service usage due to infeasibility, ensuring long-term
    stability and utility.
  </p>
  <p class="my-2">
    Revenue streams include Private Leagues, Site Sponsorship, Content Creators,
    Advertising, and Merchandise. These channels provide a balanced mix of $FPL
    and $ICP revenue, enhancing the DAO's financial resilience.
  </p>

  <h2 class="default-header mt-4">Private Leagues</h2>
  <p class="my-2">
    Private league fees in OpenFPL are charged in ICP to establish a stable
    revenue base. This approach aligns the revenue directly with the number of
    managers, ensuring it scales with user engagement.
  </p>

  <h2 class="default-header mt-4">Merchandise</h2>
  <p class="my-2">
    We have setup a shop at <a
      class="text-blue-500"
      href="https://icpga.org/shop">icpfa.org/shop</a
    > where you will be able to purchase OpenFPL merchandise in FPL or ICP. All profits
    after the promotion, marketing and production of this merchandise will be deposited
    into the DAO's treasury.
  </p>

  <h2 class="default-header">Advertising</h2>
  <p class="my-2">
    OpenFPL provides many instances to implement non-intrusive advertising to
    increase the value of the DAO. This includes on the board behind the goal on
    the pick team view along within the content subscription video reel and
    podcasting infrastructure.
  </p>

  <h2 class="default-header mt-4">Site Sponsorship</h2>
  <p class="my-2">
    Starting from August 2025, following the conclusion of the sponsorship deal
    with OpenChat, OpenFPL will offer the site sponsorship rights for bidding
    through the DAO. This will open opportunities for interested parties to
    become the named sponsor for an entire season.
  </p>
  <p class="my-2">
    Each year, sponsors can submit their bids to become the main site sponsor
    for the upcoming season, offering any ICRC-1 currency. Once a sponsor is
    selected, their exclusive rights will be secure for the entirety of that
    season. The DAO will not allow further proposals for site sponsorship until
    the subsequent preseason, ensuring the sponsor's exclusive visibility and
    association with OpenFPL.
  </p>
  <p class="my-2">
    All sponsorship revenue will be directed into the DAO's treasury,
    contributing to the financial health and sustainability of OpenFPL.
  </p>

  <h2 class="default-header mt-4">Content Creators</h2>
  <p class="my-2">
    OpenFPL will create a platform for content creators that is designed to both
    empower creators and enhance the utility of the FPL token. Creators will
    produce fantasy football-related content and share it on OpenFPL. This
    content will be available through a video reel format accessible to all
    users.
  </p>
  <p class="my-2">
    For general reel content, creators earn from a pool of FPL tokens, allocated
    based on user likes. Creators can also offer exclusive content for
    subscribers. They will receive 95% of the FPL tokens from these
    subscriptions.
  </p>
  <p class="my-2">
    Subscriptions are purchased exclusively with FPL tokens, enhancing their
    utility. The remaining 5% from subscriptions remains in the DAO's treasury.
    This approach aligns with OpenFPL's commitment to supporting content
    creators, increasing FPL token utility, and rewarding its community of
    neuron holders.
  </p>

  <p class="my-2">
    Revenue will be generated from advertising within OpenFPL services.
    Off-chain profits generated by the ICPFA will be deposited into the DAO's
    treasury.
  </p>

  <h2 class="default-header mt-4">Revenue Redistribution Plan</h2>
  <p class="my-2">
    In line with our commitment to directly benefit neuron holders, OpenFPL will
    use up to 50% of any ICRC-1 token received by the DAO to purchase $FPL from
    exchanges each month. We will only purchase enough $FPL to burn the total
    supply back down to 100m $FPL. This is also attractive to investors as it
    will remove an inflationary pressures when holding an $FPL position.
  </p>
  <p class="my-2">
    Any remaining ICRC-1 tokens earned by the DAO will remain liquid and can be
    used for whatever the DAO decides.
  </p>
</div>
