<script lang="ts">
    import AutogeneratedCanisters from "$lib/components/canisters/autogenerated-canisters.svelte";
    import DefaultCanisters from "$lib/components/canisters/default-canisters.svelte";
    import Topups from "$lib/components/canisters/topups.svelte";
    import CyclesMinted from "$lib/components/canisters/cycles-minted.svelte";
    import Layout from "../Layout.svelte";

    let activeTab: string = "default-canisters";
    function setActiveTab(tab: string): void {
        activeTab = tab;
    }

</script>
  
<Layout>
    <div class="bg-panel rounded-md mt-4">
        <h1 class="default-header p-4">OpenFPL Cycle Management</h1>

        <ul
        class="flex bg-light-gray px-1 md:px-4 pt-2 contained-text border-b border-gray-700 mb-4"
      >
        <li
          class={`mr-1 md:mr-4 ${activeTab === "default-canisters" ? "active-tab" : ""}`}
        >
          <button
            class={`p-2 ${
              activeTab === "default-canisters" ? "text-white" : "text-gray-400"
            }`}
            on:click={() => setActiveTab("default-canisters")}
          >
            Default Canisters
          </button>
        </li>
        <li
          class={`mr-1 md:mr-4 ${activeTab === "autogenerated-canisters" ? "active-tab" : ""}`}
        >
          <button
            class={`p-2 ${
              activeTab === "autogenerated-canisters" ? "text-white" : "text-gray-400"
            }`}
            on:click={() => setActiveTab("autogenerated-canisters")}
          >
            Automatically Generated Canisters
          </button>
        </li>
        <li
          class={`mr-1 md:mr-4 ${activeTab === "topups" ? "active-tab" : ""}`}
        >
          <button
            class={`p-2 ${
              activeTab === "topups" ? "text-white" : "text-gray-400"
            }`}
            on:click={() => setActiveTab("topups")}
          >
            Topups
          </button>
        </li>
        <li
          class={`mr-1 md:mr-4 ${activeTab === "cycles-minted" ? "active-tab" : ""}`}
        >
          <button
            class={`p-2 ${
              activeTab === "cycles-minted" ? "text-white" : "text-gray-400"
            }`}
            on:click={() => setActiveTab("cycles-minted")}
          >
            Cycles Minted
          </button>
        </li>
      </ul>

        {#if activeTab === "default-canisters"}
            <DefaultCanisters />
        {:else if activeTab === "autogenerated-canisters"}
            <AutogeneratedCanisters />
        {:else if activeTab === "topups"}
            <Topups />
        {:else if activeTab === "cycles-minted"}
            <CyclesMinted />
        {/if}
    </div>
</Layout>
  