module Environment {
    public let OPENFPL_BACKEND_CANISTER_ID = "";
    public let OPENWSL_BACKEND_CANISTER_ID = "";
    public let FOOTBALL_GOD_BACKEND_CANISTER_ID = "";
    public let TRANSFER_KINGS_BACKEND_CANISTER_ID = "";
      
    public let APPROVED_FRONTEND_CANISTERS = [
        OPENFPL_BACKEND_CANISTER_ID,
        OPENWSL_BACKEND_CANISTER_ID,
        FOOTBALL_GOD_BACKEND_CANISTER_ID,
        TRANSFER_KINGS_BACKEND_CANISTER_ID
    ];
};