import React, { useState, useEffect } from 'react';
import { Container, Spinner, Row, Col, Card, Accordion, Image, Table, Button } from 'react-bootstrap';
import TokenImage from "../../../assets/tokens.png";
import { ExitIcon } from '../icons';
import { useNavigate } from 'react-router-dom';

const Whitepaper = () => {
  
  const [isLoading, setIsLoading] = useState(true);
  const navigate = useNavigate();

  useEffect(() => {
    const fetchData = async () => {
      await fetchViewData();
      setIsLoading(false);
    };
    fetchData();
  }, []);

  const fetchViewData = async () => {
    
  };
  
  return (
    isLoading ? (
      <div className="customOverlay d-flex flex-column align-items-center justify-content-center">
        <Spinner animation="border" />
        <p className='text-center mt-1'>Loading</p>
      </div>) 
      :
      <Container className="flex-grow-1 my-5">
        <Row>
          <Col md={12}>
            <Card className="mb-4">
              <Card.Header><h2 className="mt-4 mb-4">OpenFPL Whitepaper</h2></Card.Header>
              <Card.Body>
                <Card.Text>Please see below details of the OpenFPL DAO.</Card.Text>
                <Accordion>
                  <Accordion.Item eventKey="0">
                    <Accordion.Header as="h1">Product Details</Accordion.Header>
                    <Accordion.Body>
                      <p>
                        OpenFPL is a decentralised fantasy football application centred on the Premier League, powered by the Internet Computer blockchain. 
                      </p>
                      <p>
                        Targeting millions of fantasy football enthusiasts globally, OpenFPL intends to introduce a broad audience to the platform and, consequently, to the Internet Computer blockchain. 
                        Functioning as a Decentralised Autonomous Organisation (DAO), its core objective is to reward users with FPL tokens derived from the revenue generated by the DAO for engaging in fantasy football.
                      </p>
                      <p>
                        The OpenFPL fantasy football game is an open-source Progressive Web Application (PWA). 
                        Designed to work harmoniously with any device as if it were a native application, it is created with scalability at its core, automatically formulating the requisite canister infrastructure 
                        to serve potentially billions of Premier League football enthusiasts around the world.
                      </p>
                      <p>
                        The DAO primarily generates revenue from the following sources:
                      </p>
                      
                      <Table bordered className="table-fixed">
                        <colgroup>
                          <col style={{width: '30%'}} />
                          <col style={{width: '70%'}} />
                        </colgroup>
                        <thead>
                          <tr>
                            <th>Source</th>
                            <th>Description</th>
                          </tr>
                        </thead>
                        <tbody>
                          <tr>
                            <td>Advertising</td>
                            <td>Integrated advertising spaces within the OpenFPL gameplay user interface. These spaces are artfully incorporated to resemble organic sporting venue advertising locations. 
                      Neuron holders can submit proposals to rent discrete advertising on behalf of a brand in key app display areas. 
                      Advertising contracts are season-long and payable to the OpenFPL treasury in FPL. As the user base grows, the cost of these spaces escalates, 
                      making them an attractive proposition for advertisers seeking secondary exposure via players' social media screenshots.
                            </td>
                          </tr>
                          <tr>
                            <td>Diamond Membership</td>
                            <td>Diamond Membership grants users the privilege of creating private leagues for a nominal fee (regulated by the DAO).</td>
                          </tr>
                          <tr>
                            <td>Private League Bets</td>
                            <td>A minor fee in FPL is levied on users entering into a wager with other users (within private leagues).</td>
                          </tr>
                        </tbody>
                      </Table>

                      <p>The revenue generated by the DAO is distributed to users in FPL via the rewards pool.</p>

                    </Accordion.Body>
                  </Accordion.Item>
                  <Accordion.Item eventKey="1">
                    <Accordion.Header as="h1">OpenFPL DAO</Accordion.Header>
                    <Accordion.Body>
                      <p>
                        OpenFPL is fully decentralised, with its governance using an on-chain, decentralised autonomous organisation (DAO). 
                        The DAO aims to operate under the Internet Computer's Service Nervous System (SNS).
                      </p>
                      <p>
                        To maintain no reliance on third parties, the DAO manages its own Premier League event dataset used within the fantasy football game. 
                        This is curated by the DAOs neuron holders in return for FPL token rewards.
                      </p>
                      <p>
                        Neuron holders can also receive FPL rewards by valuing players. A neuron can value a player once during the season to receive FPL tokens rewards. 
                        After each valuation a players value changes.
                      </p>
                      <h4 className='mt-4'>DAO Proposals</h4>
                      <Table bordered className="table-fixed">
                        <colgroup>
                          <col style={{width: '30%'}} />
                          <col style={{width: '70%'}} />
                        </colgroup>
                        <thead>
                          <tr>
                            <th>Proposal Type</th>
                            <th>Description</th>
                          </tr>
                        </thead>
                        <tbody>
                          <tr>
                            <td>FPL Tokens</td>
                            <td>The DAO can make a proposal to burn or otherwise utilise FPL tokens within the DAO's treasury FPL ledger account.</td>
                          </tr>
                          <tr>
                            <td>ICP Tokens</td>
                            <td>The DAO can make a proposal to utilise ICP tokens within the DAO's treasury ICP ledger account.</td>
                          </tr>
                          <tr>
                            <td>Rewards and Reward Percentages</td>
                            <td>The DAO can make a proposal to update the rewards and reward percentages.</td>
                          </tr>
                          <tr>
                            <td>Private League Pricing</td>
                            <td>The DAO can make a proposal to update the price of creating private leagues.</td>
                          </tr>
                          <tr>
                            <td>Advertising Contract</td>
                            <td>The DAO can make a proposal to accept a new advertising contract for the season.</td>
                          </tr>
                          <tr>
                            <td>DAO Expenses</td>
                            <td>ICP tokens in the DAO’s treasury can be used to fund expenses provided this is voted on by the DAO.</td>
                          </tr>
                          <tr>
                            <td>Player Rating</td>
                            <td>A DAO proposal can be added to modify a players rating.</td>
                          </tr>
                          <tr>
                            <td>Player Transfers</td>
                            <td>A DAO proposal can be added to transfer players in and out of teams.</td>
                          </tr>
                          <tr>
                            <td>Amend Fixtures</td>
                            <td>A DAO proposal can be added to move fixtures between gameweeks.</td>
                          </tr>
                          <tr>
                            <td>Game Data Point</td>
                            <td>Any data point can be amended by DAO proposal.</td>
                          </tr>
                        </tbody>
                      </Table>
                      
                      <h4 className='mt-4'>DAO Rewards</h4>
                      <p>
                        Rewards are paid to users with staked neurons for providing accurate information to the system. 
                        This mechanism is used to ensure the system has no reliance on any 3rd party systems.
                      </p>
                      <p>
                        The following table shows % of the rewards pool is payable for each scenario. 
                        These values can be adjusted by the DAO.
                      </p>
                      <p>Neuron Maturity</p>
                      <p>5% of the rewards pool will be used to pay Neuron maturity</p>
                      <p>Player valuations</p>
                      <Table bordered className="table-fixed">
                        <colgroup>
                          <col style={{width: '70%'}} />
                          <col style={{width: '30%'}} />
                        </colgroup>
                        <thead>
                          <tr>
                            <th>Reward</th>
                            <th>Minted Share</th>
                          </tr>
                        </thead>
                        <tbody>
                          <tr>
                            <td>Neuron Maturity</td>
                            <td>5%</td>
                          </tr>
                          <tr>
                            <td>Evaluating Players</td>
                            <td>5%</td>
                          </tr>
                          <tr>
                            <td>Validating Game Event Data</td>
                            <td>10%</td>
                          </tr>
                          <tr>
                            <td>Data Verification Council Member Participation</td>
                            <td>5%</td>
                          </tr>
                          <tr>
                            <td>OpenFPL Gameplay Awards</td>
                            <td>75%</td>
                          </tr>
                        </tbody>
                      </Table>
                    </Accordion.Body>
                  </Accordion.Item> 
                  <Accordion.Item eventKey="2">
                    <Accordion.Header>DAO Rewards</Accordion.Header>
                    <Accordion.Body>
                      <h3>DAO Voting Rewards</h3>
                      <p>The DAO voting and gameplay rewards are funded by the annual minting of new FPL tokens and revenue generated by the DAO.</p>
                      <p>Rewards are paid to users with staked neurons for providing accurate information to the system. 
                        This mechanism is used to ensure the system has no reliance on any 3rd party systems.</p>
                      <p>The DAO rewards in the following circumstances:</p>

                      <h4 className='mt-4'>Neuron Maturity</h4>
                      <p>5% of the minted FPL is used for staked neuron maturity.</p>

                      

                      <h4 className='mt-4'>Evaluating Players</h4>
                      <p>Eligble neuron holders are able to evaluate a players value, proportional to their staked neurons voting power.</p>
                      <p>The front end is designed to provide an easy interface to quickly input information into the system. 
                        Users will be able to bulk compare players with the ability to filter by position & team to make the comparsion.
                          A player will appear in the list and the user can select to increase or decrease their price 0.1, 0.2 or 0.3. 
                          This information is entered into the player pricing formula which sets a players current price. 
                          Neurons can only vote on a players value once per season. The players ratings will be set from genesis. A DAO proposal can be added to modify a players rating.</p>

                          <Table bordered className="table-fixed">
                          <colgroup>
                            <col style={{width: '70%'}} />
                            <col style={{width: '30%'}} />
                          </colgroup>
                          <thead>
                            <tr>
                              <th>Reward</th>
                              <th>Share of Minted Validation Rewards</th>
                            </tr>
                          </thead>
                          <tbody>
                            <tr>
                              <td>Valuing a player.</td>
                              <td>100% / total players for season.</td>
                            </tr>
                          </tbody>
                        </Table>


                      <h4 className='mt-4'>Validating Game Data</h4>
                      <p>The DAO wants to remain free of 3rd party libraries. To do this it will use it's community to gather the information it needs, 
                        in return the DAO will pay rewards to users for this information.</p>
                      <p>The information is fed into the game event data formula which rewards users for being the earliest to provide the required correct information to score the gameplay.</p>
                      <p>After each game users can enter the following information withing 12 hours, provided the game data requirement remains open. 
                        After the required validation point is reached (initially set to 1,000,000 FPL votes) confirming the data. Any data point can be amended by DAO proposal.</p>
                      <p>The current data points a user can enter to earn FPL tokens are:</p>
                      <p>Ideally a sports oracle is created in which the DAO could remove this requirement and subsequent reward via a DAO proposal.</p>
                    
                      <Table bordered className="table-fixed">
                        <colgroup>
                          <col style={{width: '70%'}} />
                          <col style={{width: '30%'}} />
                        </colgroup>
                        <thead>
                          <tr>
                            <th>Reward</th>
                            <th>Share of Minted Validation Rewards</th>
                          </tr>
                        </thead>
                        <tbody>
                          <tr>
                            <td>Recording correct goal scorer & assist player for a goal, including whether the goal was an own goal.</td>
                            <td>15%</td>
                          </tr>
                          <tr>
                            <td>Recording a correct penalty being awarded, with the minute of the penality and result of the penalty.</td>
                            <td>15%</td>
                          </tr>
                          <tr>
                            <td>Recording the correct minutes played for a player.</td>
                            <td>20%</td>
                          </tr>
                          <tr>
                            <td>Recording the correct number of saves for a goal keeper in each match.</td>
                            <td>20%</td>
                          </tr>
                          <tr>
                            <td>Recording the correct time in which all players in a game received yellow or red cards along with the minute the card was given.</td>
                            <td>20%</td>
                          </tr>
                          <tr>
                            <td>The number of bonus points a player receives based on 0-3, paid out in your number is in the majority.</td>
                            <td>10%</td>
                          </tr>
                        </tbody>
                      </Table>

                      <p>Incorrect data does not get paid a reward.</p>


                      
                      <h4 className='mt-4'>OpenFPL Gameplay Rewards</h4>
                      <p>Below is the share of minted FPL gameplay rewards that are shared between the neurons at their respective voting power:</p>
                      <Table bordered className="table-fixed">
                        <colgroup>
                          <col style={{width: '70%'}} />
                          <col style={{width: '30%'}} />
                        </colgroup>
                        <thead>
                          <tr>
                            <th>Reward</th>
                            <th>Share of Minted Validation Rewards</th>
                          </tr>
                        </thead>
                        <tbody>
                          <tr>
                            <td>Highest weekly points.</td>
                            <td>50% / 38 gameweeks = ~0.26%</td>
                          </tr>
                          <tr>
                            <td>Highest season score.</td>
                            <td>25%</td>
                          </tr>
                          <tr>
                            <td>Highest weekly preferred club score.</td>
                            <td>12.5% / 20 teams = ~0.25%</td>
                          </tr>
                          <tr>
                            <td>Highest gameweek player score in your team.</td>
                            <td>12.5% / 38 gameweeks = ~0.026%</td>
                          </tr>
                        </tbody>
                      </Table>
                      
                      <h4 className='mt-4'>Data Verification Council Membership Rewards</h4>
                      <p>All data verfication council members will be rewarded proportional to their participation.</p>
                      
                      <p>All rewards and reward percentages can be adjusted by DAO proposal.</p>

                    </Accordion.Body>
                  </Accordion.Item>
                  <Accordion.Item eventKey="3">
                    <Accordion.Header>FPL Utility Token</Accordion.Header>
                    <Accordion.Body>
                      <p>OpenFPL uses its own utility token called FPL. The tokens primary purpose is for rewarding users who play OpenFPL. The FPL utility token can be used to pay for OpenFPL products and services:</p>
                      <Table bordered className="table-fixed">
                        <colgroup>
                          <col style={{width: '100%'}} />
                        </colgroup>
                        <thead>
                          <tr>
                            <th>Use</th>
                          </tr>
                        </thead>
                        <tbody>
                          <tr>
                            <td>Creating a private league.</td>
                          </tr>
                          <tr>
                            <td>Placing bets with other users or groups of users.</td>
                          </tr>
                          <tr>
                            <td>Purchasing an advertising space for a season.</td>
                          </tr>
                          <tr>
                            <td>Any future products and services voted on by the DAO.</td>
                          </tr>
                        </tbody>
                      </Table>
                    </Accordion.Body>
                  </Accordion.Item>
                  <Accordion.Item eventKey="4">
                    <Accordion.Header>Genesis Token Allocation</Accordion.Header>
                    <Accordion.Body>
                      <Container fluid>
                        <Row className="justify-content-md-center mb-3">
                          <Col md="auto">
                            <Image src={TokenImage} alt="openfpl" rounded fluid className="ml-4 mr-4 mt-4 mb-4" />
                          </Col>
                        </Row>
        
                        <Row className="mb-3">
                          <Col>
                            <h3>Decentralisation sale (25%)</h3>
                            <p>25% of the total supply will be put up for sale to decentralise the governance and raise funds for the SNS. 
                            The exact amount to be raised via this sale is undecided at this point.
                            Participants in the decentralisation sale will deposit ICP into the SNS and once the sale has completed they will receive the same proportion of 
                            FPL tokens as their share of the ICP deposited. Each participant will receive their FPL as a basket of 3 equal value neurons:
                            </p>
                            <Table bordered className="table-fixed">
                                <colgroup>
                                  <col style={{width: '100%'}} />
                                </colgroup>
                                <thead>
                                  <tr>
                                    <th>Neuron</th>
                                  </tr>
                                </thead>
                                <tbody>
                                  <tr>
                                    <td>The first neuron will have a zero dissolve delay and so be immediately disbursable to liquid FPL tokens.</td>
                                  </tr>
                                  <tr>
                                    <td>The other neurons will have dissolve delays of 1 & 2 years respectively.</td>
                                  </tr>
                                  <tr>
                                    <td>Each Community Fund participant will also receive their share of tokens as a 
                                      basket of 3 neurons with the same configuration.</td>
                                  </tr>
                                </tbody>
                              </Table>
                          </Col>
                        </Row>

                        <Row className="mb-3">
                          <Col>
                            <h3>Founders and funders (24%)</h3>
                            <p>OpenFPL's foudning development team will receive 14% of the intial token allocation. This will be split between the founding developer (10% out of the 14%) and
                              other team members (4% out of 14%). The founding developer will receive a single neuron with a 4 year disolve delay that cannot be touched until that period is 
                              over (vesting period). This ensures he cannot rug-pull investors and provides an ongoing incentive to make OpenFPL successful. The remaining team members and each 
                              Funded.app NFT purchaser will receive their FPL as a basket of 3 equal value neurons:
                            </p>
                            
                            <Table bordered className="table-fixed">
                                <colgroup>
                                  <col style={{width: '100%'}} />
                                </colgroup>
                                <thead>
                                  <tr>
                                    <th>Neuron</th>
                                  </tr>
                                </thead>
                                <tbody>
                                  <tr>
                                    <td>The first neuron will have a zero dissolve delay and so be immediately disbursable to liquid FPL tokens.</td>
                                  </tr>
                                  <tr>
                                    <td>The other neurons will have dissolve delays of 1 & 2 years respectively.</td>
                                  </tr>
                                  <tr>
                                    <td>Each Community Fund participant will also receive their share of tokens as a 
                                      basket of 3 neurons with the same configuration.</td>
                                  </tr>
                                </tbody>
                              </Table>

                              <p>Confirmed team members are:</p>
                              <ul>
                                <li>James Beadle: Lead Developer (10m $FPL)</li>
                                <li>@ICP_Insider: Community Support (1m $FPL)</li>
                                <li>@daydrinkr: Community Manager (500K $FPL)</li>
                                <li>@madmaxic: FPL Expert (500K $FPL)</li>
                                <li>TBC: 2m $FPL</li>
                              </ul>

                          </Col>
                        </Row>

                        <Row className="mb-3">
                          <Col>
                            <h3>Treasury (51%)</h3>
                            <p>After the decentraliation sale the SNS will be left with a treasury of the remaining 51% of FPL tokens. 80% of the FPL & ICP tokens in the treasury will be staked for the maximum amount of time in their respective SNS.
                              The remainder is likely to be used over time to automatically reward users who positively contribute and help OpenFPL grow by playing OpenFPL. 
                              <br />
                              <br />
                              It will also be available to pay community bounties, by SNS proposal, to compensate people who contribute to OpenFPL more generally. 
                              This could be used for instance to reward 3rd party developers for code contributions.
                              <br />
                              <br />
                              A small portion, around 2%, will be used to provide initial liquidity pools for DEXes (decentralised exchanges). 
                              In order for FPL tokens to be traded it is necessary to list FPL on one or more exchanges. 
                              The intention is to trade on IC based DEXes. 
                              To list FPL on a DEX implementing an AMM it is necessary to provide a liquidity pool of FPL backed by another token, in our case ICP raised from the decentralisation sale. 
                              We plan to make FPL available on several DEXes as and when they are available. 
                              For each DEX it will be necessary to create a proposal to transfer some FPL from the SNS to the DEX, and another proposal to transfer an equal value of ICP from the SNS to the DEX.
                            </p>
                          </Col>
                        </Row>
                        <Row className="mb-3">
                          <Col>
                            <h3>Initial SNS Configuration</h3>
                            <Table bordered className="table-fixed">
                              <colgroup>
                                <col style={{width: '70%'}} />
                                <col style={{width: '30%'}} />
                              </colgroup>
                              <thead>
                                <tr>
                                  <th>Configuration</th>
                                  <th>Value</th>
                                </tr>
                              </thead>
                              <tbody>
                                <tr>
                                  <td>Transaction fee in FPL tokens that must be paid for ledger transfers</td>
                                  <td>0.001</td>
                                </tr>
                                <tr>
                                  <td>Number of FPL tokens that a rejected proposal costs the proposer</td>
                                  <td>10</td>
                                </tr>
                                <tr>
                                  <td>Minimum number of FPL tokens that can be staked in a neuron</td>
                                  <td>10</td>
                                </tr>
                                <tr>
                                  <td>Maximum voting period for a proposal</td>
                                  <td>7 days</td>
                                </tr>
                                <tr>
                                  <td>Proportion of voting power needed for a proposal to be accepted</td>
                                  <td>5%</td>
                                </tr>
                                <tr>
                                  <td>Minimum neuron dissolve delay to vote</td>
                                  <td>1 month</td>
                                </tr>
                                <tr>
                                  <td>Maximum neuron dissolve delay</td>
                                  <td>4 years</td>
                                </tr>
                                <tr>
                                  <td>Maximum dissolve delay bonus</td>
                                  <td>2x</td>
                                </tr>
                                <tr>
                                  <td>Maximum age for age bonus</td>
                                  <td>6 months</td>
                                </tr>
                                <tr>
                                  <td>Maximum age bonus</td>
                                  <td>1.25x</td>
                                </tr>
                                <tr>
                                  <td>Percentage of total supply that will be generated annually for rewards</td>
                                  <td>2.5%</td>
                                </tr>
                              </tbody>
                            </Table>
                          </Col>
                        </Row>

                        <Row className="mb-3">
                          <Col>
                            <h3>SNS Decentralisation Sale Configuration</h3>
                            <Table bordered className="table-fixed">
                              <colgroup>
                                <col style={{width: '70%'}} />
                                <col style={{width: '30%'}} />
                              </colgroup>
                              <thead>
                                <tr>
                                  <th>Configuration</th>
                                  <th>Value</th>
                                </tr>
                              </thead>
                              <tbody>
                                <tr>
                                  <td>The total number of FPL tokens to be sold</td>
                                  <td>25,000,000 (25%)</td>
                                </tr>
                                <tr>
                                  <td>The maximum ICP to be raised</td>
                                  <td>TBC</td>
                                </tr>
                                <tr>
                                  <td>The minimum ICP to be raised (otherwise sale fails and ICP returned)</td>
                                  <td>TBC</td>
                                </tr>
                                <tr>
                                  <td>The ICP to come from the Community Fund</td>
                                  <td>TBC</td>
                                </tr>
                                <tr>
                                  <td>End date of sale (unless maximum ICP raised sooner)</td>
                                  <td>TBC</td>
                                </tr>
                                <tr>
                                  <td>Minimum number of sale participants</td>
                                  <td>500</td>
                                </tr>
                                <tr>
                                  <td>Minimum ICP per buyer</td>
                                  <td>1</td>
                                </tr>
                                <tr>
                                  <td>Maximum ICP per buyer</td>
                                  <td>TBC</td>
                                </tr>
                              </tbody>
                            </Table>
                          </Col>
                        </Row>

                        <Row className="mb-3">
                          <Col>
                            <h3>Valuation Range</h3>
                            <p>The reason to impose a maximum target is to give participants a minimum bound on the number of FPL tokens they will receive for their ICP investment.</p>
                          </Col>
                        </Row>
                      </Container>
                    </Accordion.Body>
                  </Accordion.Item>
                  <Accordion.Item eventKey="5">
                    <Accordion.Header>OpenFPL Treasury</Accordion.Header>
                    <Accordion.Body>
                      <p>The SNS will hold a treasury of ICP tokens and FPL tokens. Immediately after the decentralisation sale the SNS will have an ICP ledger account with the 
                        ICP raised in the sale and an FPL ledger account with 51M tokens. The plan for these FPL tokens is described above but the treasury is available to be used
                          by the DAO through proposals as it sees fit.</p>
                      <p>Soon after the decentralisation sale, as and when DEXes are available, proposals will be made to transfer FPL and the corresponding value of ICP from 
                          the treasury into a handful of AMM liquidity pools. This will enable the trading of FPL.</p>
                      <p>We plan to create a proposal to stake a large portion of ICP as an 8 year neuron. This neuron would participate in NNS voting by following an OpenFPL 
                        beacon neuron which would seek to influence the ICs agenda to suit the long term interests of the OpenFPL DAO. 
                        It would also earn voting rewards for the DAO which could be used to cover ongoing costs or build up a reserve. 
                        This all depends on whether a small but significant change is made to the IC to allow canisters to control neurons.
                        Any liquid ICP in the reserve could be used directly, or the DAO could swap FPL from the FPL reserve for ICP at a DEX, 
                        and use it to fund expenses such as cycles for hosting, 3rd party services, and later for paying the development team.</p>
                      
                      <h4 className='mt-4'>ICP for cycles to fund hosting</h4>

                      <p>OpenFPL has a "cycles dispenser" canister which keeps all the other OpenFPL canisters topped up with cycles. 
                        It has a treasury of cycles and ICP. 
                        When it is runnning low on cycles it will automatically burn some ICP for more cycles using the NNS cycles minting canister. 
                        There will be infrequent proposals to transfer a portion of ICP from the SNS treasury to the "cycles dispenser".
                      </p>
                      <h4 className='mt-4'>3rd party services</h4>
                      <p>
                        The intention is for OpenFPL to have no off-chain dependencies so that it is not necessary to trust any human agent, 
                        for example to transact in FIAT currencies. There are no plans to add any off-chain dependencies.
                      </p>
                      <h4 className='mt-4'>Pay the development team</h4>
                      <p>
                        For some period the founding developer will continue to develop on the OpenFPL platform and thus remain a core contributor to the OpenFPL open source project. 
                        Eventually the OpenFPL DAO will need to fund its own development. In this case development team(s) can make proposals to the SNS to receive ICP for development. 
                        For example the team could make a proposal each quarter with a development plan and a request for funds.
                      </p>

                      <h4 className='mt-4'>Mitigation against a 51% Attack</h4>

                      <p>
                        There is a danger that the OpenFPL SNS treasury could be the target of an attack. One possible scenario is for an attacker to buy a large proportion 
                        of the FPL tokens in the decentralisation sale and immediately increase the dissolve delay of all of their neurons to the maximum 4 year in an attempt to gain
                        more than 50% of the SNS voting power. If successful they could force through a proposal to transfer the entire ICP and FPL treasury to themselves. 
                        The Community Fund actually provides a great deal of mitigation against this scenario because it limits the proportion of voting power an attacker 
                        would be able to acquire.
                      </p>
                    </Accordion.Body>
                  </Accordion.Item>
                  <Accordion.Item eventKey="6">
                    <Accordion.Header>Tokenomics</Accordion.Header>
                    <Accordion.Body>
                      <h4 className='mt-4'>Total supply levers</h4>
                      <p>
                        At genesis the total supply of FPL tokens will be 100M. 
                        The supply will increase if more tokens are minted and decrease if tokens are burned.
                      </p>
                      <p>
                        The SNS is configured to generate 2.5% of the total supply annually to pay equally to the 4 reward categories specified in the "DAO Rewards" section.
                        Voting rewards accumulate in participating neurons as maturity . 
                        At the point a neuron’s maturity is disbursed it is burned and the corresponding value of FPL tokens will be minted by the SNS ledger to an account. 
                        It is also possible for the SNS to mint tokens by proposal although it is unlikely the OpenFPL DAO will elect to do this.
                      </p>

                      <p>The only way the SNS can burn tokens is by proposal.</p>

                      <h4 className='mt-4'>Income and outgoings</h4>

                      <p>At genesis the SNS will have a treasury of ICP from the decentralisation sale and 51M FPL tokens.</p>
                      <p>The SNS will receive an income in FPL tokens from premium features, transaction fees and advertising revenue. 
                        The SNS will also receive an income in ICP from the NNS voting rewards of its large ICP neuron assuming that goes ahead.</p>
                      <p>The SNS will have various outgoings. It will use ICP to pay the OpenFPL dapp hosting costs (cycles), 3rd parties for services, 
                        and at some point soon, the core dev team. It will use FPL to pay user rewards and community bounties.</p>
                      <p>In the early years, outgoings will outstrip income and the FPL treasury will largely be used to fund user rewards and community bounties. 
                        The expectation is that as income grows over time it will eventually balance outgoings. 
                        A higher income would also allow a higher rate of user rewards and bounties to encourage higher growth in users and usage.</p>
                      <p>
                        As the OpenFPL DAO sees fit it can choose to burn FPL tokens to reduce the total supply. 
                        The expectation is that over several years the SNS will be able to afford to burn FPL at an increasing rate until the burn rate exceeds 
                        the minting rate from voting rewards and the total supply starts decreasing.
                      </p>

                      <h4 className='mt-4'>Token price</h4>
                      <p>There are various factors that will influence the price of FPL tokens such as:</p>
                      <p>- Total supply</p>
                      <p>- Market sentiment</p>
                      <p>- Income</p>
                      <p>- Costs</p>
                      <p>- Liquid supply</p>

                      <p>We have discussed total supply but arguably liquid supply is a bigger factor when considering the token price.</p>

                      <p>After the decentralisation sale, participants and funded.app NFT holders will receive a basket of neurons of varying dissolve delays with only 1/3 being immediately liquid. 
                        The voting reward rate, initialised to 2.5%, is expected to encourage token holders to lock up a certain proportion of tokens thus, at least temporarily, 
                        removing them from the liquid supply. In the case of the founding develper, his 14% is vested for 4 years.</p>
                      <p>There are various tokenomics parameters which can affect the proportion of FPL that is locked up. 
                        These include the max dissolve delay, the dissolve delay bonus, min dissolve delay to vote, max age, max age bonus, and voting reward rate. 
                        We have carefully chosen initial values for these parameters which we believe provide a good balance of incentives but these are all levers available to the DAO 
                        to allow it to influence the total and liquid supply and therefore the price if so desired.</p>
                      <p>Consider the SNS treasury of FPL tokens. These tokens are liquid but are only being trickled out (in percentage terms) to the community as user rewards and bounties, 
                        and then only some proportion will find their way onto the market (DEXes). It is a similar story for the portion of FPL held in the NNS reserve - 
                        it is liquid but will not enter the market unless the DAO decides to conduct a future sale.</p>
                      <p>As a general rule the DAO will want the price of the token to rise over time but this has to be balanced against other factors such as the growth of the app. 
                        For instance it might be desirable in some circumstances to turn the user reward taps up higher to encourage more user growth but in the short term that could 
                        negatively impact price by increasing the liquid supply.</p>

                    </Accordion.Body>
                  </Accordion.Item>
                  <Accordion.Item eventKey="7">
                    <Accordion.Header>Data Verification Council</Accordion.Header>
                    <Accordion.Body>
                      <h4 className='mt-4'>OpenFPL Data Verification Council</h4>
                      <p>
                        One of the challenges faced by the DAO will be to ensure the accuracy of its data. 
                        The DAO does not wish to rely on third parties but it will use third party data feeds as a secondary check on data.
                      </p>
                      <p>The DAO will vote in members of a Data Verification Council that will be responsible for checking that data is valid.
                      Council members can be removed by DAO proposal at any time. 
                      </p>

                      <p>
                        Council members will access the data verification dashboard showing instances in which variations in data occur. The variations 
                        are identified from publicly available API datafeeds which can be added and removed by DAO vote.</p>
                      <p>DAO users who verify data will receive a reputation score, this will enable the DAO to select the most accurate people to participate with the council. </p>
                      <p>Council members are awarded $FPL tokens for their participation from the DAO rewards.</p>
                    </Accordion.Body>
                  </Accordion.Item>
                  <Accordion.Item eventKey="8">
                    <Accordion.Header>Roadmap</Accordion.Header>
                    <Accordion.Body>
                      <h4 className='mt-4'>OpenFPL RoadMap</h4>
                      <p>- Q4 2023: OpenFPL fantasy football beta launch.</p>
                      <p>- Q1 2024: OpenFPL DAO Player Evaluation Launch.</p>
                      <p>- Q2 2024: OpenFPL SNS Decentralisation Sale.</p>
                      <p>- Q3 2024: OpenFPL public launch.</p>
                    </Accordion.Body>
                  </Accordion.Item>
                  <Accordion.Item eventKey="9">
                    <Accordion.Header>Other Links</Accordion.Header>
                    <Accordion.Body>
                      <Row className="mt-4">
                        <p> <a href="https://github.com/jamesbeadle/OpenFPL" target='_blank'>Github</a>. <ExitIcon /></p>
                      </Row>
                      <Container fluid>
                        <Row className="mt-4">
                          <Col>
                            <Button className='btn nav-link-brand' onClick={() => navigate('/gameplay')}>
                              Open FPL Gameplay Rules
                            </Button>
                          </Col>
                        </Row>
                        <Row className="mt-4">
                          <Col>
                            <Button className='btn nav-link-brand' onClick={() => navigate('/architecture')}>
                              OpenFPL Architecture.
                            </Button>
                          </Col>
                        </Row>
                        <Row className="mt-4">
                          <Col>
                            <Button className='btn nav-link-brand' onClick={() => navigate('/definitions')}>
                              Further Definitions.
                            </Button>
                          </Col>
                        </Row>
                        <Row className="mt-4">
                          <Col>
                            <Button className='btn nav-link-brand' onClick={() => navigate('/terms')}>
                              Terms and Conditions.
                            </Button>
                          </Col>  
                        </Row>
                      </Container>
                    </Accordion.Body>
                  </Accordion.Item>
                </Accordion>
              </Card.Body>
            </Card>
          </Col>
        </Row>
      </Container>
    );
};

export default Whitepaper;
