import React from 'react';
import { 
  AD, AE, AF, AG, AI, AL, AM, AO, AQ, AR, AS, AT, AU, AW, AX, AZ, 
  BA, BB, BD, BE, BF, BG, BH, BI, BJ, BL, BM, BN, BO, BQ, BR, BS, BT, BV, BW, BY, BZ, 
  CA, CC, CD, CF, CG, CH, CI, CK, CL, CM, CN, CO, CR, CU, CV, CW, CX, CY, CZ, 
  DE, DJ, DK, DM, DO, DZ, 
  EC, EE, EG, EH, ER, ES, ET, 
  FI, FJ, FK, FM, FO, FR, 
  GA, GB, GD, GE, GF, GG, GH, GI, GL, GM, GN, GP, GQ, GR, GS, GT, GU, GW, GY, 
  HK, HM, HN, HR, HT, HU, 
  ID, IE, IL, IM, IN, IO, IQ, IR, IS, IT, 
  JE, JM, JO, JP, 
  KE, KG, KH, KI, KM, KN, KP, KR, KW, KY, KZ, 
  LA, LB, LC, LI, LK, LR, LS, LT, LU, LV, LY, 
  MA, MC, MD, ME, MF, MG, MH, MK, ML, MM, MN, MO, MP, MQ, MR, MS, MT, MU, MV, MW, MX, MY, MZ, 
  NA, NC, NE, NF, NG, NI, NL, NO, NP, NR, NU, NZ, 
  OM, 
  PA, PE, PF, PG, PH, PK, PL, PM, PN, PR, PS, PT, PW, PY, 
  QA, 
  RE, RO, RS, RU, RW, 
  SA, SB, SC, SD, SE, SG, SH, SI, SJ, SK, SL, SM, SN, SO, SR, SS, ST, SV, SX, SY, SZ, 
  TC, TD, TF, TG, TH, TJ, TK, TL, TM, TN, TO, TR, TT, TV, TW, TZ, 
  UA, UG, UM, US, UY, UZ, 
  VA, VC, VE, VG, VI, VN, VU, 
  WF, WS, 
  YE, YT, 
  ZA, ZM, ZW 
} from 'country-flag-icons/react/3x2';
const countryNameToCode = {
    'Albania': 'AL',
    'Algeria': 'DZ',
    'Argentina': 'AR',
    'Australia': 'AU',
    'Austria': 'AT',
    'Belgium': 'BE',
    'Bosnia and Herzegovina': 'BA',
    'Brazil': 'BR',
    'Burkina Faso': 'BF',
    'Cameroon': 'CM',
    'Canada': 'CA',
    'Colombia': 'CO',
    'Costa Rica': 'CR',
    'Ivory Coast': 'CI',
    'Croatia': 'HR',
    'Czech Republic': 'CZ',
    'Denmark': 'DK',
    'DR Congo': 'CD',
    'Ecuador': 'EC',
    'Egypt': 'EG',
    'England': 'GB',
    'Estonia': 'EE',
    'Finland': 'FI',
    'France': 'FR',
    'Gabon': 'GA',
    'Germany': 'DE',
    'Ghana': 'GH',
    'Greece': 'GR',
    'Grenada': 'GD',
    'Guinea': 'GN',
    'Iceland': 'IS',
    'Iran': 'IR',
    'Ireland': 'IE',
    'Israel': 'IL',
    'Italy': 'IT',
    'Ivory Coast': 'CI',
    'Jamaica': 'JM',
    'Japan': 'JP',
    'Macedonia': 'MK',
    'Mali': 'ML',
    'Mexico': 'MX',
    'Montserrat': 'MS',
    'Morocco': 'MA',
    'Netherlands': 'NL',
    'Nigeria': 'NG',
    'Northern Ireland': 'GB',
    'Norway': 'NO',
    'Paraguay': 'PY',
    'Poland': 'PL',
    'Portugal': 'PT',
    'Scotland': 'GB',
    'Senegal': 'SN',
    'Serbia': 'RS',
    'Slovakia': 'SK',
    'South Africa': 'ZA',
    'South Korea': 'KR',
    'Spain': 'ES',
    'Sweden': 'SE',
    'Switzerland': 'CH',
    'Tunisia': 'TN',
    'Turkey': 'TR',
    'Ukraine': 'UA',
    'United States': 'US',
    'Uruguay': 'UY',
    'Wales': 'GB',
    'Zimbabwe': 'ZW',
  };
  
// Create an object that maps the flags to the country codes
const flags = {
    'AD': <AD title='Andorra' style={{width: "20px"}} />,
    'AE': <AE title='United Arab Emirates' style={{width: "20px"}} />,
    'AF': <AF title='Afghanistan' style={{width: "20px"}} />,
    'AG': <AG title='Antigua and Barbuda' style={{width: "20px"}} />,
    'AI': <AI title='Anguilla' style={{width: "20px"}} />,
    'AL': <AL title='Albania' style={{width: "20px"}} />,
    'AM': <AM title='Armenia' style={{width: "20px"}} />,
    'AO': <AO title='Angola' style={{width: "20px"}} />,
    'AQ': <AQ title='Antarctica' style={{width: "20px"}} />,
    'AR': <AR title='Argentina' style={{width: "20px"}} />,
    'AS': <AS title='American Samoa' style={{width: "20px"}} />,
    'AT': <AT title='Austria' style={{width: "20px"}} />,
    'AU': <AU title='Australia' style={{width: "20px"}} />,
    'AW': <AW title='Aruba' style={{width: "20px"}} />,
    'AX': <AX title='Åland Islands' style={{width: "20px"}} />,
    'AZ': <AZ title='Azerbaijan' style={{width: "20px"}} />,
    'BA': <BA title='Bosnia and Herzegovina' style={{width: "20px"}} />,
    'BB': <BB title='Barbados' style={{width: "20px"}} />,
    'BD': <BD title='Bangladesh' style={{width: "20px"}} />,
    'BE': <BE title='Belgium' style={{width: "20px"}} />,
    'BF': <BF title='Burkina Faso' style={{width: "20px"}} />,
    'BG': <BG title='Bulgaria' style={{width: "20px"}} />,
    'BH': <BH title='Bahrain' style={{width: "20px"}} />,
    'BI': <BI title='Burundi' style={{width: "20px"}} />,
    'BJ': <BJ title='Benin' style={{width: "20px"}} />,
    'BL': <BL title='Saint Barthélemy' style={{width: "20px"}} />,
    'BM': <BM title='Bermuda' style={{width: "20px"}} />,
    'BN': <BN title='Brunei Darussalam' style={{width: "20px"}} />,
    'BO': <BO title='Bolivia (Plurinational State of)' style={{width: "20px"}} />,
    'BQ': <BQ title='Bonaire, Sint Eustatius and Saba' style={{width: "20px"}} />,
    'BR': <BR title='Brazil' style={{width: "20px"}} />,
    'BS': <BS title='Bahamas' style={{width: "20px"}} />,
    'BT': <BT title='Bhutan' style={{width: "20px"}} />,
    'BV': <BV title='Bouvet Island' style={{width: "20px"}} />,
    'BW': <BW title='Botswana' style={{width: "20px"}} />,
    'BY': <BY title='Belarus' style={{width: "20px"}} />,
    'BZ': <BZ title='Belize' style={{width: "20px"}} />,
    'CA': <CA title='Canada' style={{width: "20px"}} />,
    'CC': <CC title='Cocos (Keeling) Islands' style={{width: "20px"}} />,
    'CD': <CD title='Congo, Democratic Republic of the' style={{width: "20px"}} />,
    'CF': <CF title='Central African Republic' style={{width: "20px"}} />,
    'CG': <CG title='Congo' style={{width: "20px"}} />,
    'CH': <CH title='Switzerland' style={{width: "20px"}} />,
    'CI': <CI title='Ivory Coast' style={{width: "20px"}} />,
    'CK': <CK title='Cook Islands' style={{width: "20px"}} />,
    'CL': <CL title='Chile' style={{width: "20px"}} />,
    'CM': <CM title='Cameroon' style={{width: "20px"}} />,
    'CN': <CN title='China' style={{width: "20px"}} />,
    'CO': <CO title='Colombia' style={{width: "20px"}} />,
    'CR': <CR title='Costa Rica' style={{width: "20px"}} />,
    'CU': <CU title='Cuba' style={{width: "20px"}} />,
    'CV': <CV title='Cabo Verde' style={{width: "20px"}} />,
    'CW': <CW title='Curaçao' style={{width: "20px"}} />,
    'CX': <CX title='Christmas Island' style={{width: "20px"}} />,
    'CY': <CY title='Cyprus' style={{width: "20px"}} />,
    'CZ': <CZ title='Czechia' style={{width: "20px"}} />,
    'DE': <DE title='Germany' style={{width: "20px"}} />,
    'DJ': <DJ title='Djibouti' style={{width: "20px"}} />,
    'DK': <DK title='Denmark' style={{width: "20px"}} />,
    'DM': <DM title='Dominica' style={{width: "20px"}} />,
    'DO': <DO title='Dominican Republic' style={{width: "20px"}} />,
    'DZ': <DZ title='Algeria' style={{width: "20px"}} />,
    'EC': <EC title='Ecuador' style={{width: "20px"}} />,
    'EE': <EE title='Estonia' style={{width: "20px"}} />,
    'EG': <EG title='Egypt' style={{width: "20px"}} />,
    'EH': <EH title='Western Sahara' style={{width: "20px"}} />,
    'ER': <ER title='Eritrea' style={{width: "20px"}} />,
    'ES': <ES title='Spain' style={{width: "20px"}} />,
    'ET': <ET title='Ethiopia' style={{width: "20px"}} />,
    'FI': <FI title='Finland' style={{width: "20px"}} />,
    'FJ': <FJ title='Fiji' style={{width: "20px"}} />,
    'FK': <FK title='Falkland Islands (Malvinas)' style={{width: "20px"}} />,
    'FM': <FM title='Micronesia, Federated States of' style={{width: "20px"}} />,
    'FO': <FO title='Faroe Islands' style={{width: "20px"}} />,
    'FR': <FR title='France' style={{width: "20px"}} />,
    'GA': <GA title='Gabon' style={{width: "20px"}} />,
    'GB': <GB title='United Kingdom' style={{width: "20px"}} />,
    'GD': <GD title='Grenada' style={{width: "20px"}} />,
    'GE': <GE title='Georgia' style={{width: "20px"}} />,
    'GF': <GF title='French Guiana' style={{width: "20px"}} />,
    'GG': <GG title='Guernsey' style={{width: "20px"}} />,
    'GH': <GH title='Ghana' style={{width: "20px"}} />,
    'GI': <GI title='Gibraltar' style={{width: "20px"}} />,
    'GL': <GL title='Greenland' style={{width: "20px"}} />,
    'GM': <GM title='Gambia' style={{width: "20px"}} />,
    'GN': <GN title='Guinea' style={{width: "20px"}} />,
    'GP': <GP title='Guadeloupe' style={{width: "20px"}} />,
    'GQ': <GQ title='Equatorial Guinea' style={{width: "20px"}} />,
    'GR': <GR title='Greece' style={{width: "20px"}} />,
    'GS': <GS title='South Georgia and the South Sandwich Islands' style={{width: "20px"}} />,
    'GT': <GT title='Guatemala' style={{width: "20px"}} />,
    'GU': <GU title='Guam' style={{width: "20px"}} />,
    'GW': <GW title='Guinea-Bissau' style={{width: "20px"}} />,
    'GY': <GY title='Guyana' style={{width: "20px"}} />,
    'HK': <HK title='Hong Kong' style={{width: "20px"}} />,
    'HM': <HM title='Heard Island and McDonald Islands' style={{width: "20px"}} />,
    'HN': <HN title='Honduras' style={{width: "20px"}} />,
    'HR': <HR title='Croatia' style={{width: "20px"}} />,
    'HT': <HT title='Haiti' style={{width: "20px"}} />,
    'HU': <HU title='Hungary' style={{width: "20px"}} />,
    'ID': <ID title='Indonesia' style={{width: "20px"}} />,
    'IE': <IE title='Ireland' style={{width: "20px"}} />,
    'IL': <IL title='Israel' style={{width: "20px"}} />,
    'IM': <IM title='Isle of Man' style={{width: "20px"}} />,
    'IN': <IN title='India' style={{width: "20px"}} />,
    'IO': <IO title='British Indian Ocean Territory' style={{width: "20px"}} />,
    'IQ': <IQ title='Iraq' style={{width: "20px"}} />,
    'IR': <IR title='Iran, Islamic Republic of' style={{width: "20px"}} />,
    'IS': <IS title='Iceland' style={{width: "20px"}} />,
    'IT': <IT title='Italy' style={{width: "20px"}} />,
    'JE': <JE title='Jersey' style={{width: "20px"}} />,
    'JM': <JM title='Jamaica' style={{width: "20px"}} />,
    'JO': <JO title='Jordan' style={{width: "20px"}} />,
    'JP': <JP title='Japan' style={{width: "20px"}} />,
    'KE': <KE title='Kenya' style={{width: "20px"}} />,
    'KG': <KG title='Kyrgyzstan' style={{width: "20px"}} />,
    'KH': <KH title='Cambodia' style={{width: "20px"}} />,
    'KI': <KI title='Kiribati' style={{width: "20px"}} />,
    'KM': <KM title='Comoros' style={{width: "20px"}} />,
    'KN': <KN title='Saint Kitts and Nevis' style={{width: "20px"}} />,
    'KP': <KP title='South Korea' style={{width: "20px"}} />,
    'KR': <KR title='North Korea' style={{width: "20px"}} />,
    'KW': <KW title='Kuwait' style={{width: "20px"}} />,
    'KY': <KY title='Cayman Islands' style={{width: "20px"}} />,
    'KZ': <KZ title='Kazakhstan' style={{width: "20px"}} />,
    'LA': <LA title='Lao Peoples Democratic Republic' style={{width: "20px"}} />,
    'LB': <LB title='Lebanon' style={{width: "20px"}} />,
    'LC': <LC title='Saint Lucia' style={{width: "20px"}} />,
    'LI': <LI title='Liechtenstein' style={{width: "20px"}} />,
    'LK': <LK title='Sri Lanka' style={{width: "20px"}} />,
    'LR': <LR title='Liberia' style={{width: "20px"}} />,
    'LS': <LS title='Lesotho' style={{width: "20px"}} />,
    'LT': <LT title='Lithuania' style={{width: "20px"}} />,
    'LU': <LU title='Luxembourg' style={{width: "20px"}} />,
    'LV': <LV title='Latvia' style={{width: "20px"}} />,
    'LY': <LY title='Libya' style={{width: "20px"}} />,
    'MA': <MA title='Morocco' style={{width: "20px"}} />,
    'MC': <MC title='Monaco' style={{width: "20px"}} />,
    'MD': <MD title='Moldova, Republic of' style={{width: "20px"}} />,
    'ME': <ME title='Montenegro' style={{width: "20px"}} />,
    'MF': <MF title='Saint Martin (French part)' style={{width: "20px"}} />,
    'MG': <MG title='Madagascar' style={{width: "20px"}} />,
    'MH': <MH title='Marshall Islands' style={{width: "20px"}} />,
    'MK': <MK title='North Macedonia' style={{width: "20px"}} />,
    'ML': <ML title='Mali' style={{width: "20px"}} />,
    'MM': <MM title='Myanmar' style={{width: "20px"}} />,
    'MN': <MN title='Mongolia' style={{width: "20px"}} />,
    'MO': <MO title='Macao' style={{width: "20px"}} />,
    'MP': <MP title='Northern Mariana Islands' style={{width: "20px"}} />,
    'MQ': <MQ title='Martinique' style={{width: "20px"}} />,
    'MR': <MR title='Mauritania' style={{width: "20px"}} />,
    'MS': <MS title='Montserrat' style={{width: "20px"}} />,
    'MT': <MT title='Malta' style={{width: "20px"}} />,
    'MU': <MU title='Mauritius' style={{width: "20px"}} />,
    'MV': <MV title='Maldives' style={{width: "20px"}} />,
    'MW': <MW title='Malawi' style={{width: "20px"}} />,
    'MX': <MX title='Mexico' style={{width: "20px"}} />,
    'MY': <MY title='Malaysia' style={{width: "20px"}} />,
    'MZ': <MZ title='Mozambique' style={{width: "20px"}} />,
    'NA': <NA title='Namibia' style={{width: "20px"}} />,
    'NC': <NC title='New Caledonia' style={{width: "20px"}} />,
    'NE': <NE title='Niger' style={{width: "20px"}} />,
    'NF': <NF title='Norfolk Island' style={{width: "20px"}} />,
    'NG': <NG title='Nigeria' style={{width: "20px"}} />,
    'NI': <NI title='Nicaragua' style={{width: "20px"}} />,
    'NL': <NL title='Netherlands' style={{width: "20px"}} />,
    'NO': <NO title='Norway' style={{width: "20px"}} />,
    'NP': <NP title='Nepal' style={{width: "20px"}} />,
    'NR': <NR title='Nauru' style={{width: "20px"}} />,
    'NU': <NU title='Niue' style={{width: "20px"}} />,
    'NZ': <NZ title='New Zealand' style={{width: "20px"}} />,
    'OM': <OM title='Oman' style={{width: "20px"}} />,
    'PA': <PA title='Panama' style={{width: "20px"}} />,
    'PE': <PE title='Peru' style={{width: "20px"}} />,
    'PF': <PF title='French Polynesia' style={{width: "20px"}} />,
    'PG': <PG title='Papua New Guinea' style={{width: "20px"}} />,
    'PH': <PH title='Philippines' style={{width: "20px"}} />,
    'PK': <PK title='Pakistan' style={{width: "20px"}} />,
    'PL': <PL title='Poland' style={{width: "20px"}} />,
    'PM': <PM title='Saint Pierre and Miquelon' style={{width: "20px"}} />,
    'PN': <PN title='Pitcairn' style={{width: "20px"}} />,
    'PR': <PR title='Puerto Rico' style={{width: "20px"}} />,
    'PS': <PS title='Palestine, State of' style={{width: "20px"}} />,
    'PT': <PT title='Portugal' style={{width: "20px"}} />,
    'PW': <PW title='Palau' style={{width: "20px"}} />,
    'PY': <PY title='Paraguay' style={{width: "20px"}} />,
    'QA': <QA title='Qatar' style={{width: "20px"}} />,
    'RE': <RE title='Réunion' style={{width: "20px"}} />,
    'RO': <RO title='Romania' style={{width: "20px"}} />,
    'RS': <RS title='Serbia' style={{width: "20px"}} />,
    'RU': <RU title='Russian Federation' style={{width: "20px"}} />,
    'RW': <RW title='Rwanda' style={{width: "20px"}} />,
    'SA': <SA title='Saudi Arabia' style={{width: "20px"}} />,
    'SB': <SB title='Solomon Islands' style={{width: "20px"}} />,
    'SC': <SC title='Seychelles' style={{width: "20px"}} />,
    'SD': <SD title='Sudan' style={{width: "20px"}} />,
    'SE': <SE title='Sweden' style={{width: "20px"}} />,
    'SG': <SG title='Singapore' style={{width: "20px"}} />,
    'SH': <SH title='Saint Helena, Ascension and Tristan da Cunha' style={{width: "20px"}} />,
    'SI': <SI title='Slovenia' style={{width: "20px"}} />,
    'SJ': <SJ title='Svalbard and Jan Mayen' style={{width: "20px"}} />,
    'SK': <SK title='Slovakia' style={{width: "20px"}} />,
    'SL': <SL title='Sierra Leone' style={{width: "20px"}} />,
    'SM': <SM title='San Marino' style={{width: "20px"}} />,
    'SN': <SN title='Senegal' style={{width: "20px"}} />,
    'SO': <SO title='Somalia' style={{width: "20px"}} />,
    'SR': <SR title='Suriname' style={{width: "20px"}} />,
    'SS': <SS title='South Sudan' style={{width: "20px"}} />,
    'ST': <ST title='Sao Tome and Principe' style={{width: "20px"}} />,
    'SV': <SV title='El Salvador' style={{width: "20px"}} />,
    'SX': <SX title='Sint Maarten (Dutch part)' style={{width: "20px"}} />,
    'SY': <SY title='Syrian Arab Republic' style={{width: "20px"}} />,
    'SZ': <SZ title='Eswatini' style={{width: "20px"}} />,
    'TC': <TC title='Turks and Caicos Islands' style={{width: "20px"}} />,
    'TD': <TD title='Chad' style={{width: "20px"}} />,
    'TF': <TF title='French Southern Territories' style={{width: "20px"}} />,
    'TG': <TG title='Togo' style={{width: "20px"}} />,
    'TH': <TH title='Thailand' style={{width: "20px"}} />,
    'TJ': <TJ title='Tajikistan' style={{width: "20px"}} />,
    'TK': <TK title='Tokelau' style={{width: "20px"}} />,
    'TL': <TL title='Timor-Leste' style={{width: "20px"}} />,
    'TM': <TM title='Turkmenistan' style={{width: "20px"}} />,
    'TN': <TN title='Tunisia' style={{width: "20px"}} />,
    'TO': <TO title='Tonga' style={{width: "20px"}} />,
    'TR': <TR title='Turkey' style={{width: "20px"}} />,
    'TT': <TT title='Trinidad and Tobago' style={{width: "20px"}} />,
    'TV': <TV title='Tuvalu' style={{width: "20px"}} />,
    'TW': <TW title='Taiwan, Province of China' style={{width: "20px"}} />,
    'TZ': <TZ title='Tanzania, United Republic of' style={{width: "20px"}} />,
    'UA': <UA title='Ukraine' style={{width: "20px"}} />,
    'UG': <UG title='Uganda' style={{width: "20px"}} />,
    'UM': <UM title='United States Minor Outlying Islands' style={{width: "20px"}} />,
    'US': <US title='United States' style={{width: "20px"}} />,
    'UY': <UY title='Uruguay' style={{width: "20px"}} />,
    'UZ': <UZ title='Uzbekistan' style={{width: "20px"}} />,
    'VA': <VA title='Holy See (Vatican City State)' style={{width: "20px"}} />,
    'VC': <VC title='Saint Vincent and the Grenadines' style={{width: "20px"}} />,
    'VE': <VE title='Venezuela, Bolivarian Republic of' style={{width: "20px"}} />,
    'VG': <VG title='Virgin Islands, British' style={{width: "20px"}} />,
    'VI': <VI title='Virgin Islands, U.S.' style={{width: "20px"}} />,
    'VN': <VN title='Vietnam' style={{width: "20px"}} />,
    'VU': <VU title='Vanuatu' style={{width: "20px"}} />,
    'WF': <WF title='Wallis and Futuna' style={{width: "20px"}} />,
    'WS': <WS title='Samoa' style={{width: "20px"}} />,
    'YE': <YE title='Yemen' style={{width: "20px"}} />,
    'YT': <YT title='Mayotte' style={{width: "20px"}} />,
    'ZA': <ZA title='South Africa' style={{width: "20px"}} />,
    'ZM': <ZM title='Zambia' style={{width: "20px"}} />,
    'ZW': <ZW title='Zimbabwe' style={{width: "20px"}} />
  };

  const getFlag = (countryName) => {
    // Get the alpha-2 code
    const code = countryNameToCode[countryName];
    // Return the flag component, or null if the country is not in our mapping
    return flags[code] || null;
  }

export default getFlag;

