import React from 'react';
import { 
  AD, AE, AF, AG, AI, AL, AM, AO, AQ, AR, AS, AT, AU, AW, AX, AZ, 
  BA, BB, BD, BE, BF, BG, BH, BI, BJ, BL, BM, BN, BO, BQ, BR, BS, BT, BV, BW, BY, BZ, 
  CA, CC, CD, CF, CG, CH, CI, CK, CL, CM, CN, CO, CR, CU, CV, CW, CX, CY, CZ, 
  DE, DJ, DK, DM, DO, DZ, 
  EC, EE, EG, EH, ER, ES, ET, 
  FI, FJ, FK, FM, FO, FR, 
  GA, GB, GD, GE, GF, GG, GH, GI, GL, GM, GN, GP, GQ, GR, GS, GT, GU, GW, GY, 
  HK, HM, HN, HR, HT, HU, 
  ID, IE, IL, IM, IN, IO, IQ, IR, IS, IT, 
  JE, JM, JO, JP, 
  KE, KG, KH, KI, KM, KN, KP, KR, KW, KY, KZ, 
  LA, LB, LC, LI, LK, LR, LS, LT, LU, LV, LY, 
  MA, MC, MD, ME, MF, MG, MH, MK, ML, MM, MN, MO, MP, MQ, MR, MS, MT, MU, MV, MW, MX, MY, MZ, 
  NA, NC, NE, NF, NG, NI, NL, NO, NP, NR, NU, NZ, 
  OM, 
  PA, PE, PF, PG, PH, PK, PL, PM, PN, PR, PS, PT, PW, PY, 
  QA, 
  RE, RO, RS, RU, RW, 
  SA, SB, SC, SD, SE, SG, SH, SI, SJ, SK, SL, SM, SN, SO, SR, SS, ST, SV, SX, SY, SZ, 
  TC, TD, TF, TG, TH, TJ, TK, TL, TM, TN, TO, TR, TT, TV, TW, TZ, 
  UA, UG, UM, US, UY, UZ, 
  VA, VC, VE, VG, VI, VN, VU, 
  WF, WS, 
  YE, YT, 
  ZA, ZM, ZW 
} from 'country-flag-icons/react/3x2';
const countryNameToCode = {
    'Albania': 'AL',
    'Algeria': 'DZ',
    'Argentina': 'AR',
    'Australia': 'AU',
    'Austria': 'AT',
    'Belgium': 'BE',
    'Bosnia and Herzegovina': 'BA',
    'Brazil': 'BR',
    'Burkina Faso': 'BF',
    'Cameroon': 'CM',
    'Canada': 'CA',
    'Colombia': 'CO',
    'Costa Rica': 'CR',
    'Ivory Coast': 'CI',
    'Croatia': 'HR',
    'Czech Republic': 'CZ',
    'Denmark': 'DK',
    'DR Congo': 'CD',
    'Ecuador': 'EC',
    'Egypt': 'EG',
    'England': 'GB',
    'Estonia': 'EE',
    'Finland': 'FI',
    'France': 'FR',
    'Gabon': 'GA',
    'Germany': 'DE',
    'Ghana': 'GH',
    'Greece': 'GR',
    'Grenada': 'GD',
    'Guinea': 'GN',
    'Iceland': 'IS',
    'Iran': 'IR',
    'Ireland': 'IE',
    'Israel': 'IL',
    'Italy': 'IT',
    'Ivory Coast': 'CI',
    'Jamaica': 'JM',
    'Japan': 'JP',
    'Macedonia': 'MK',
    'Mali': 'ML',
    'Mexico': 'MX',
    'Montserrat': 'MS',
    'Morocco': 'MA',
    'Netherlands': 'NL',
    'Nigeria': 'NG',
    'Northern Ireland': 'GB',
    'Norway': 'NO',
    'Paraguay': 'PY',
    'Poland': 'PL',
    'Portugal': 'PT',
    'Scotland': 'GB',
    'Senegal': 'SN',
    'Serbia': 'RS',
    'Slovakia': 'SK',
    'South Africa': 'ZA',
    'South Korea': 'KR',
    'Spain': 'ES',
    'Sweden': 'SE',
    'Switzerland': 'CH',
    'Tunisia': 'TN',
    'Turkey': 'TR',
    'Ukraine': 'UA',
    'United States': 'US',
    'Uruguay': 'UY',
    'Wales': 'GB',
    'Zimbabwe': 'ZW',
  };
  
// Create an object that maps the flags to the country codes
const flags = {
    'AD': <AD title='Andorra'  />,
    'AE': <AE title='United Arab Emirates'  />,
    'AF': <AF title='Afghanistan'  />,
    'AG': <AG title='Antigua and Barbuda'  />,
    'AI': <AI title='Anguilla'  />,
    'AL': <AL title='Albania'  />,
    'AM': <AM title='Armenia'  />,
    'AO': <AO title='Angola'  />,
    'AQ': <AQ title='Antarctica'  />,
    'AR': <AR title='Argentina'  />,
    'AS': <AS title='American Samoa'  />,
    'AT': <AT title='Austria'  />,
    'AU': <AU title='Australia'  />,
    'AW': <AW title='Aruba'  />,
    'AX': <AX title='Åland Islands'  />,
    'AZ': <AZ title='Azerbaijan'  />,
    'BA': <BA title='Bosnia and Herzegovina'  />,
    'BB': <BB title='Barbados'  />,
    'BD': <BD title='Bangladesh'  />,
    'BE': <BE title='Belgium'  />,
    'BF': <BF title='Burkina Faso'  />,
    'BG': <BG title='Bulgaria'  />,
    'BH': <BH title='Bahrain'  />,
    'BI': <BI title='Burundi'  />,
    'BJ': <BJ title='Benin'  />,
    'BL': <BL title='Saint Barthélemy'  />,
    'BM': <BM title='Bermuda'  />,
    'BN': <BN title='Brunei Darussalam'  />,
    'BO': <BO title='Bolivia (Plurinational State of)'  />,
    'BQ': <BQ title='Bonaire, Sint Eustatius and Saba'  />,
    'BR': <BR title='Brazil'  />,
    'BS': <BS title='Bahamas'  />,
    'BT': <BT title='Bhutan'  />,
    'BV': <BV title='Bouvet Island'  />,
    'BW': <BW title='Botswana'  />,
    'BY': <BY title='Belarus'  />,
    'BZ': <BZ title='Belize'  />,
    'CA': <CA title='Canada'  />,
    'CC': <CC title='Cocos (Keeling) Islands'  />,
    'CD': <CD title='Congo, Democratic Republic of the'  />,
    'CF': <CF title='Central African Republic'  />,
    'CG': <CG title='Congo'  />,
    'CH': <CH title='Switzerland'  />,
    'CI': <CI title='Ivory Coast'  />,
    'CK': <CK title='Cook Islands'  />,
    'CL': <CL title='Chile'  />,
    'CM': <CM title='Cameroon'  />,
    'CN': <CN title='China'  />,
    'CO': <CO title='Colombia'  />,
    'CR': <CR title='Costa Rica'  />,
    'CU': <CU title='Cuba'  />,
    'CV': <CV title='Cabo Verde'  />,
    'CW': <CW title='Curaçao'  />,
    'CX': <CX title='Christmas Island'  />,
    'CY': <CY title='Cyprus'  />,
    'CZ': <CZ title='Czechia'  />,
    'DE': <DE title='Germany'  />,
    'DJ': <DJ title='Djibouti'  />,
    'DK': <DK title='Denmark'  />,
    'DM': <DM title='Dominica'  />,
    'DO': <DO title='Dominican Republic'  />,
    'DZ': <DZ title='Algeria'  />,
    'EC': <EC title='Ecuador'  />,
    'EE': <EE title='Estonia'  />,
    'EG': <EG title='Egypt'  />,
    'EH': <EH title='Western Sahara'  />,
    'ER': <ER title='Eritrea'  />,
    'ES': <ES title='Spain'  />,
    'ET': <ET title='Ethiopia'  />,
    'FI': <FI title='Finland'  />,
    'FJ': <FJ title='Fiji'  />,
    'FK': <FK title='Falkland Islands (Malvinas)'  />,
    'FM': <FM title='Micronesia, Federated States of'  />,
    'FO': <FO title='Faroe Islands'  />,
    'FR': <FR title='France'  />,
    'GA': <GA title='Gabon'  />,
    'GB': <GB title='United Kingdom'  />,
    'GD': <GD title='Grenada'  />,
    'GE': <GE title='Georgia'  />,
    'GF': <GF title='French Guiana'  />,
    'GG': <GG title='Guernsey'  />,
    'GH': <GH title='Ghana'  />,
    'GI': <GI title='Gibraltar'  />,
    'GL': <GL title='Greenland'  />,
    'GM': <GM title='Gambia'  />,
    'GN': <GN title='Guinea'  />,
    'GP': <GP title='Guadeloupe'  />,
    'GQ': <GQ title='Equatorial Guinea'  />,
    'GR': <GR title='Greece'  />,
    'GS': <GS title='South Georgia and the South Sandwich Islands'  />,
    'GT': <GT title='Guatemala'  />,
    'GU': <GU title='Guam'  />,
    'GW': <GW title='Guinea-Bissau'  />,
    'GY': <GY title='Guyana'  />,
    'HK': <HK title='Hong Kong'  />,
    'HM': <HM title='Heard Island and McDonald Islands'  />,
    'HN': <HN title='Honduras'  />,
    'HR': <HR title='Croatia'  />,
    'HT': <HT title='Haiti'  />,
    'HU': <HU title='Hungary'  />,
    'ID': <ID title='Indonesia'  />,
    'IE': <IE title='Ireland'  />,
    'IL': <IL title='Israel'  />,
    'IM': <IM title='Isle of Man'  />,
    'IN': <IN title='India'  />,
    'IO': <IO title='British Indian Ocean Territory'  />,
    'IQ': <IQ title='Iraq'  />,
    'IR': <IR title='Iran, Islamic Republic of'  />,
    'IS': <IS title='Iceland'  />,
    'IT': <IT title='Italy'  />,
    'JE': <JE title='Jersey'  />,
    'JM': <JM title='Jamaica'  />,
    'JO': <JO title='Jordan'  />,
    'JP': <JP title='Japan'  />,
    'KE': <KE title='Kenya'  />,
    'KG': <KG title='Kyrgyzstan'  />,
    'KH': <KH title='Cambodia'  />,
    'KI': <KI title='Kiribati'  />,
    'KM': <KM title='Comoros'  />,
    'KN': <KN title='Saint Kitts and Nevis'  />,
    'KP': <KP title='South Korea'  />,
    'KR': <KR title='North Korea'  />,
    'KW': <KW title='Kuwait'  />,
    'KY': <KY title='Cayman Islands'  />,
    'KZ': <KZ title='Kazakhstan'  />,
    'LA': <LA title='Lao Peoples Democratic Republic'  />,
    'LB': <LB title='Lebanon'  />,
    'LC': <LC title='Saint Lucia'  />,
    'LI': <LI title='Liechtenstein'  />,
    'LK': <LK title='Sri Lanka'  />,
    'LR': <LR title='Liberia'  />,
    'LS': <LS title='Lesotho'  />,
    'LT': <LT title='Lithuania'  />,
    'LU': <LU title='Luxembourg'  />,
    'LV': <LV title='Latvia'  />,
    'LY': <LY title='Libya'  />,
    'MA': <MA title='Morocco'  />,
    'MC': <MC title='Monaco'  />,
    'MD': <MD title='Moldova, Republic of'  />,
    'ME': <ME title='Montenegro'  />,
    'MF': <MF title='Saint Martin (French part)'  />,
    'MG': <MG title='Madagascar'  />,
    'MH': <MH title='Marshall Islands'  />,
    'MK': <MK title='North Macedonia'  />,
    'ML': <ML title='Mali'  />,
    'MM': <MM title='Myanmar'  />,
    'MN': <MN title='Mongolia'  />,
    'MO': <MO title='Macao'  />,
    'MP': <MP title='Northern Mariana Islands'  />,
    'MQ': <MQ title='Martinique'  />,
    'MR': <MR title='Mauritania'  />,
    'MS': <MS title='Montserrat'  />,
    'MT': <MT title='Malta'  />,
    'MU': <MU title='Mauritius'  />,
    'MV': <MV title='Maldives'  />,
    'MW': <MW title='Malawi'  />,
    'MX': <MX title='Mexico'  />,
    'MY': <MY title='Malaysia'  />,
    'MZ': <MZ title='Mozambique'  />,
    'NA': <NA title='Namibia'  />,
    'NC': <NC title='New Caledonia'  />,
    'NE': <NE title='Niger'  />,
    'NF': <NF title='Norfolk Island'  />,
    'NG': <NG title='Nigeria'  />,
    'NI': <NI title='Nicaragua'  />,
    'NL': <NL title='Netherlands'  />,
    'NO': <NO title='Norway'  />,
    'NP': <NP title='Nepal'  />,
    'NR': <NR title='Nauru'  />,
    'NU': <NU title='Niue'  />,
    'NZ': <NZ title='New Zealand'  />,
    'OM': <OM title='Oman'  />,
    'PA': <PA title='Panama'  />,
    'PE': <PE title='Peru'  />,
    'PF': <PF title='French Polynesia'  />,
    'PG': <PG title='Papua New Guinea'  />,
    'PH': <PH title='Philippines'  />,
    'PK': <PK title='Pakistan'  />,
    'PL': <PL title='Poland'  />,
    'PM': <PM title='Saint Pierre and Miquelon'  />,
    'PN': <PN title='Pitcairn'  />,
    'PR': <PR title='Puerto Rico'  />,
    'PS': <PS title='Palestine, State of'  />,
    'PT': <PT title='Portugal'  />,
    'PW': <PW title='Palau'  />,
    'PY': <PY title='Paraguay'  />,
    'QA': <QA title='Qatar'  />,
    'RE': <RE title='Réunion'  />,
    'RO': <RO title='Romania'  />,
    'RS': <RS title='Serbia'  />,
    'RU': <RU title='Russian Federation'  />,
    'RW': <RW title='Rwanda'  />,
    'SA': <SA title='Saudi Arabia'  />,
    'SB': <SB title='Solomon Islands'  />,
    'SC': <SC title='Seychelles'  />,
    'SD': <SD title='Sudan'  />,
    'SE': <SE title='Sweden'  />,
    'SG': <SG title='Singapore'  />,
    'SH': <SH title='Saint Helena, Ascension and Tristan da Cunha'  />,
    'SI': <SI title='Slovenia'  />,
    'SJ': <SJ title='Svalbard and Jan Mayen'  />,
    'SK': <SK title='Slovakia'  />,
    'SL': <SL title='Sierra Leone'  />,
    'SM': <SM title='San Marino'  />,
    'SN': <SN title='Senegal'  />,
    'SO': <SO title='Somalia'  />,
    'SR': <SR title='Suriname'  />,
    'SS': <SS title='South Sudan'  />,
    'ST': <ST title='Sao Tome and Principe'  />,
    'SV': <SV title='El Salvador'  />,
    'SX': <SX title='Sint Maarten (Dutch part)'  />,
    'SY': <SY title='Syrian Arab Republic'  />,
    'SZ': <SZ title='Eswatini'  />,
    'TC': <TC title='Turks and Caicos Islands'  />,
    'TD': <TD title='Chad'  />,
    'TF': <TF title='French Southern Territories'  />,
    'TG': <TG title='Togo'  />,
    'TH': <TH title='Thailand'  />,
    'TJ': <TJ title='Tajikistan'  />,
    'TK': <TK title='Tokelau'  />,
    'TL': <TL title='Timor-Leste'  />,
    'TM': <TM title='Turkmenistan'  />,
    'TN': <TN title='Tunisia'  />,
    'TO': <TO title='Tonga'  />,
    'TR': <TR title='Turkey'  />,
    'TT': <TT title='Trinidad and Tobago'  />,
    'TV': <TV title='Tuvalu'  />,
    'TW': <TW title='Taiwan, Province of China'  />,
    'TZ': <TZ title='Tanzania, United Republic of'  />,
    'UA': <UA title='Ukraine'  />,
    'UG': <UG title='Uganda'  />,
    'UM': <UM title='United States Minor Outlying Islands'  />,
    'US': <US title='United States'  />,
    'UY': <UY title='Uruguay'  />,
    'UZ': <UZ title='Uzbekistan'  />,
    'VA': <VA title='Holy See (Vatican City State)'  />,
    'VC': <VC title='Saint Vincent and the Grenadines'  />,
    'VE': <VE title='Venezuela, Bolivarian Republic of'  />,
    'VG': <VG title='Virgin Islands, British'  />,
    'VI': <VI title='Virgin Islands, U.S.'  />,
    'VN': <VN title='Vietnam'  />,
    'VU': <VU title='Vanuatu'  />,
    'WF': <WF title='Wallis and Futuna'  />,
    'WS': <WS title='Samoa'  />,
    'YE': <YE title='Yemen'  />,
    'YT': <YT title='Mayotte'  />,
    'ZA': <ZA title='South Africa'  />,
    'ZM': <ZM title='Zambia'  />,
    'ZW': <ZW title='Zimbabwe'  />
  };

const getFlag = (countryName, className='player-modal-flag') => {
  console.log(className)
  const code = countryNameToCode[countryName];
  if (flags[code]) {
    return React.cloneElement(flags[code], { className });
  }
  return null;
};
  

export default getFlag;

